<?php
	mb_internal_encoding("UTF-8");

	define("INSTAGRAM_CLIENT_ID", "XXXXXXXXXXXXXXXXXXXXX");
	define("INSTAGRAM_CLIENT_SECRET", "XXXXXXXXXXXXXXXXXXXXX");

	define("INSTAGRAM_ACCESS_TOKEN", "XXXXXXXXXXXXXXXXXXXXX");

	define("INSTAGRAM_API_SUCCESS_CODE", 200);

	define("DB_NAME", "XXXXXXXXXXXXXXXXXXXXX");
	define("DB_HOST", "XXXXXXXXXXXXXXXXXXXXX");
	define("DB_USER", "XXXXXXXXXXXXXXXXXXXXX");
	define("DB_USER_PASSWORD", "XXXXXXXXXXXXXXXXXXXXX");

	define("SETTING_RECENT_POSTS_CUTOFF_INDEX", 2);
	define('SETTING_POSTS_PER_PAGE', 12);

	define("SITEURL", "XXXXXXXXXXXXXXXXXXXXX");
?>